routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Route::get('/logout', 'Auth\LoginController@logout')->name('logout');

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/', 'HomeController@index')->name('home');
Route::get('/premium/employer', 'HomeController@employerPremium')->name('premium.employer');

Route::group(['middleware' => ['guest.redirect']], function () {

    // registration
    Route::get('/register/maid', 'RegisterEmployeeController@create')->name('register.employee.create');
    Route::post('/register/maid', 'RegisterEmployeeController@store')->name('register.employee.store');

    Route::get('/register/employer', 'RegisterEmployerController@create')->name('register.employer.create');
    Route::post('/register/employer', 'RegisterEmployerController@store')->name('register.employer.store');

    Route::group(['prefix' => 'employee'], function () {

        Route::resource('search', 'Employee\SearchController', ['as' => 'employee']);

    });

});

// please add route that need to login below
// please use resourcefull route for standard
Route::group(['middleware' => ['auth']], function () {

    Route::group(['prefix' => 'user'], function () {

        Route::resource('profile_picture', 'ProfilePictureController');
        Route::resource('account', 'AccountController', ['as' => 'profile']);

    });

    Route::group(['prefix' => 'employee'], function () {

        Route::resource('personal', 'Employee\PersonalInformationController', ['as' => 'employee']);
        Route::resource('job_details', 'Employee\JobDetailsController', ['as' => 'employee']);
    });

    Route::group(['prefix' => 'employer'], function () {

        Route::resource('personal', 'Employer\PersonalInformationController', ['as' => 'employer']);
        Route::resource('job_details', 'Employer\JobDetailsController', ['as' => 'employer']);
    });

    Route::resource('user', 'UserController');

    Route::group(['middleware' => ['admin'], 'prefix' => 'admin'], function () {

        Route::resource('dashboard', 'Admin\DashboardController', ['as' => 'admin']);

        Route::put('employee/{id}/verify', 'Admin\EmployeeController@verify')->name('admin.employee.verify');
        Route::put('employee/{id}/unverify', 'Admin\EmployeeController@unverify')->name('admin.employee.unverify');
        Route::resource('employee', 'Admin\EmployeeController', ['as' => 'admin']);

        Route::put('employer/{id}/verify', 'Admin\EmployerController@verify')->name('admin.employer.verify');
        Route::put('employer/{id}/unverify', 'Admin\EmployerController@unverify')->name('admin.employer.unverify');
        Route::resource('employer', 'Admin\EmployerController', ['as' => 'admin']);

    });

});

//test

Route::get('/print', 'PrintController@print');

app/Models/Employer.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Lecturize\Addresses\Traits\HasAddresses;

class Employer extends Model
{
    use HasAddresses, SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'display_name',

        'height',
        'weight',
        'marital_status',
        'has_children',

        'religion_id',
        'religion_other',
        'nationality_id',
        'nationality_other',
        'race_id',
        'race_other',

        'location_type',
        'employee_types',
        'employee_types_other',
        'work_skill_others',
        'households',
        'job',
        'salary_monthly',
        'salary_daily',
        'salary_hourly',
        'about',

        'phone',
        'phone_2',
        'facebook',
        'linkedin',
        'google_plus',
    ];

    protected $dates = ['deleted_at'];
    protected $casts = [
        'employee_types'    => 'array',
        'work_skill_others' => 'array',
        'households'        => 'json',
    ];

    public function user()
    {
        return $this->morphOne(User::class, 'userable');
    }

    public function workskills()
    {
        return $this->belongsToMany(WorkSkill::class);
    }

    public function getIsCompleteAttribute()
    {
        if ($this->attributes['is_profile_completed'] == 1) {
            return true;
        } else {
            return false;
        }
    }

    public function getLocationTypeNameAttribute()
    {
        if ($this->attributes['location_type'] == 'h') {
            return 'Home';
        } else if ($this->attributes['location_type'] == 's') {
            return 'shop';
        } else if ($this->attributes['location_type'] == 'o') {
            return 'Office';
        } else {
            return 'not set';
        }
    }

    public function getEmployeeTypesNameAttribute()
    {
        if (!empty($this->attributes['employee_types'])) {

            $employee_types = json_decode($this->attributes['employee_types']);
            $types          = [];

            foreach ($employee_types as $type) {

                if ($type == 'ft1') {

                    array_push($types, 'Fulltime (live together)');

                } else if ($type == 'ft2') {

                    array_push($types, 'Fulltime (not live together. shuttle everyday)');

                } else if ($type == 'pt') {

                    array_push($types, 'Parttime (not everyday)');

                }

            }

            return $types;

        } else {
            return 'not set';
        }

    }
}

app/Http/Controllers/Admin/EmployerController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Country;
use App\Models\Employer;
use App\Models\Nationality;
use App\Models\Race;
use App\Models\State;
use Carbon\Carbon;
use Illuminate\Http\Request;

class EmployerController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $employees = Employer::all();

        $data = [
            // 'breadcrumb' => [
            //     ['Admin', '#'],
            //     ['Employer', '#'],
            // ],
            'employers' => $employees,
        ];

        return view('admin.employer.index')->with($data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $employer = Employer::find($id);

        $detail = [
            'name'         => $employer->user->name,
            'display name' => $employer->display_name,
            'height'       => $employer->height . 'cm',
            'weight'       => $employer->weight . 'kg',
            'nationality'  => $employer->nationality_name,
            'race'         => $employer->race_name,
        ];

        $data = [
            'employer' => $employer,
            'details'  => $detail,
        ];

        return view('admin.employer.show')->with($data);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $employer      = Employer::find($id);
        $countries     = Country::toJsonOption();
        $nationalities = Nationality::toJsonOption();
        $races         = Race::toJsonOption();
        $states        = State::toJsonOption('name', 'name');
        $address       = $employee->getPrimaryAddress();

        $data = [
            'breadcrumb'    => [
                ['Admin', route('admin.employer.index')],
                ['Employer', route('admin.employer.index')],
                ['Update', '#'],
            ],
            'action'        => route('admin.employer.update', $id),
            'method'        => 'PUT',
            'employer'      => $employer,
            'address'       => $address,
            'countries'     => $countries,
            'nationalities' => $nationalities,
            'races'         => $races,
            'states'        => $states,
        ];

        return view('admin.employer.form')->with($data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function verify($id)
    {
        $employer = Employer::find($id);
        $user     = $employer->user;

        $user->verified = Carbon::now();
        $user->save();

        return response()->json([
            'success' => 'Employer verified',
        ]);
    }

    public function unverify($id)
    {
        $employer = Employer::find($id);
        $user     = $employer->user;

        $user->verified = null;
        $user->save();

        return response()->json([
            'success' => 'Employer unverified',
        ]);
    }
}

app/Http/Controllers/Employer/JobDetailsController.php
<?php

namespace App\Http\Controllers\Employer;

use App\Http\Controllers\Controller;
use App\Models\WorkSkill;
use Illuminate\Http\Request;

class JobDetailsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $user                 = auth()->user();
        $employee             = $user->userable;
        $employee_work_skills = $employee->workSkills->map(function ($item, $key) {
            return $item->id;
        })->toArray();
        $work_skills = WorkSkill::all();

        // dd($user->userable->workSkills->map(function ($item, $key) {
        //     return $item->id;
        // }));

        $data = [
            'user'                 => $user,
            'employer'             => $employee,
            'employee_work_skills' => $employee_work_skills,
            'work_skills'          => $work_skills,
        ];

        return view('employer.job_details')->with($data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $user     = auth()->user();
        $employer = $user->userable;

        if (!empty($request['skills'])) {
            $request['skills'] = array_keys($request['skills']);
        } else {
            $request['skills'] = [];
        }

        // dd($request->all());

        $employer->update(
            [
                'about'          => $request['about'],
                'location_type'  => $request['location_type'],
                'households'     => $request['households'],
                'employee_types' => $request['employee_types'],

                'salary_monthly' => $request['salary_monthly'],
                'salary_daily'   => $request['salary_daily'],
                'salary_hourly'  => $request['salary_hourly'],
            ]
        );

        $employer->workSkills()->detach();
        $employer->workSkills()->attach($request['skills']);

        \Session::flash('alert-success', 'Employer Related Information Updated');
        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Employer/PersonalInformationController.php
<?php

namespace App\Http\Controllers\Employer;

use App\Http\Controllers\Controller;
use App\Http\Requests\EmployerPersonalRequest;
use App\Models\Country;
use App\Models\Employer;
use App\Models\Nationality;
use App\Models\Race;
use App\Models\State;
use Illuminate\Http\Request;

class PersonalInformationController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $user     = auth()->user();
        $employer = $user->userable;

        if (empty($employer)) {
            $employer                       = new Employer();
            $employer->is_profile_completed = false;
            $employer->save();

            $user->userable_id   = $employer->id;
            $user->userable_type = Employer::class;
            $user->save();
        }

        $address = $employer->getPrimaryAddress();

        $countries      = Country::toJsonOption();
        $nationalities  = Nationality::toJsonOption();
        $races          = Race::toJsonOption();
        $states         = State::toJsonOption('name', 'name');
        $marital_status = json_encode([
            ['text' => 'Never married', 'value' => 1],
            ['text' => 'Married', 'value' => 2],
            ['text' => 'Divorced', 'value' => 3],
            ['text' => 'Separated', 'value' => 4],
            ['text' => 'Widowed', 'value' => 5],
        ]);

        $data = [
            'user'           => $user,
            'employer'       => $employer,
            'address'        => $address,
            'countries'      => $countries,
            'nationalities'  => $nationalities,
            'races'          => $races,
            'states'         => $states,
            'marital_status' => $marital_status,
        ];

        return view('profile.employer_details')->with($data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     *
     * @return \Illuminate\Http\Response
     */
    public function store(EmployerPersonalRequest $request)
    {
        // dd($request->all());

        $user     = auth()->user();
        $employer = $user->userable;

        $user->update(
            [
                'name' => $request['name'],
            ]
        );

        $employer->update(
            [
                'display_name'   => $request['display_name'],
                'nationality_id' => $request['nationality_id'],
                'race_id'        => $request['race_id'],

                'facebook'       => $request['facebook'],
                'linkedin'       => $request['linkedin'],
                'google_plus'    => $request['google_plus'],
            ]
        );

        $address = [
            'street'       => $request['street'],
            'street_extra' => $request['street_extra'],
            'state'        => $request['state'],
            'city'         => $request['city'],
            'post_code'    => $request['post_code'],
            'country_id'   => $request['country_id'],
            'is_primary'   => true,
        ];

        if ($employer->hasAddress()) {
            $current_address = $employer->addresses()->first();
            $employer->updateAddress($current_address, $address);
        } else {
            $employer->addAddress($address);
        }

        $employer->is_profile_completed = 1;
        $employer->save();

        \Session::flash('alert-success', 'Personal Information Updated');

        return redirect()->back();
    }
}

resources/views/employer/alert.blade.php
@if(!$user->is_activated)
<div class="alert alert-danger" role="alert">
Your account is not activate yet, please wait until admin activate your account.
</div>
@endif

@if(!$employer->isComplete)
<div class="alert alert-danger" role="alert">
Please complete your profile!
</div>
@endif

resources/views/employer/job_details.blade.php
@extends('layouts.app2')

@section('content')

@include('employer.alert')

<div class="row">
    <div class="col-md-4">

        @include('profile.profile_card')

    </div>
    <div class="col-md-8">

        <div class="card" style="min-height:100%;">

            <!-- Card content -->
            <div class="card-body text-left">

                <!--begin::Form-->
                <form id="form-job-related-details" action="{{ route('employer.job_details.store') }}" method="post" v-cloak>

                    <!-- Title -->
                    <button type="button" class="btn btn-sm btn-indigo mt-0 float-right" v-on:click="editMode" v-if="!edit">Edit</button>
                    <button type="button" class="btn btn-sm btn-blue-grey mt-0 float-right" v-on:click="viewMode" v-if="edit">Cancel</button>
                    <button type="submit" class="btn btn-sm btn-primary mt-0 float-right" v-if="edit">Save</button>
                    <h4 class="card-title"><a>Employer Related Information</a></h4>
                    <hr>

                    @if(isset($method))
                    {{ method_field($method) }}
                    @endif
                    {{ csrf_field() }}

                    <b-form-group horizontal :label-cols="3" label="About">
                        <textarea name="about" class="form-control" :readonly="!edit">{{ $employer->about or old('about') }}</textarea>
                    </b-form-group>

                    <b-form-group horizontal :label-cols="3" label="Location Type">
                        <input value="{{ $employer->location_type_name or old('location_type') }}" class="form-control" readonly v-if="!edit">
                        <select name="location_type" class="mdb-select" :class="(!edit)? 'd-none':''" placeholder="Not set">
                            <option value="" disabled selected>Choose location type</option>
                            <option value="h">House</option>
                            <option value="s">Shop</option>
                            <option value="o">Office</option>
                        </select>
                    </b-form-group>

                    <b-form-group horizontal :label-cols="3" label="Household(s)">
                        <button type="button" class="btn btn-sm btn-default" v-if="edit" v-on:click="addHousehold">
                            <i class="fa fa-plus"></i>
                        </button>

                        <div class="form-group row" v-for="(household, key) in households">
                            <label class="col-sm-3 col-form-label">@{{ key+1 }}. Age<span v-if="!edit">: @{{ households[key] }}</span></label>
                            <div class="col-sm-6" v-if="edit">
                                <div class="input-group input-group-sm">
                                    <input name="households[]" type="text" class="form-control" v-model="households[key]">
                                    <div class="input-group-append">
                                        <button class="btn btn-danger" type="button" v-on:click="removeHousehold(key)">Remove</button>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </b-form-group>

                    <b-form-group horizontal :label-cols="3" label="Maid type">

                        @foreach( $employer->employee_types_name as $employee_type )
                        <input value="{{ $employee_type }}" class="form-control" readonly v-if="!edit" {{ !empty($employee->has_children)? 'checked':null }}>
                        @endforeach

                        <select name="employee_types[]" class="mdb-select" multiple :class="(!edit)? 'd-none':''" placeholder="Not set">
                            <option value="" disabled selected>Choose maid type</option>
                            <option value="ft1">Fulltime (live together)</option>
                            <option value="ft2">Fulltime (not live together. Shuttle everyday)</option>
                            <option value="pt">Parttime (not everyday)</option>
                        </select>
                    </b-form-group>

                    <b-form-group horizontal :label-cols="3" label="Other maid type">
                        <input name="employee_types_other" value="{{ $employer->employee_types_other or old('employee_types_other') }}" class="form-control" placeholder="specify" :readonly="!edit">
                    </b-form-group>

                    <h4 class="card-title"><a>Skills</a></h4>
                    <hr>

                    @foreach($work_skills as $skill)
                    <b-form-group horizontal :label-cols="8" label="{{ $skill->name }}">
                        <div class="switch" v-if="edit">
                            <label>
                                <input name="skills[{{ $skill->id }}]" type="checkbox" {{ in_array($skill->id, $employee_work_skills)? 'checked':null }} >
                                <span class="lever"></span>
                            </label>
                        </div>
                        <input class="form-control" value="{{ in_array($skill->id, $employee_work_skills)? 'Yes':'No' }}" readonly v-if="!edit">
                    </b-form-group>
                    @endforeach

                    <h4 class="card-title"><a>Salary</a></h4>
                    <hr>

                    <b-form-group horizontal :label-cols="2" label="Monthly (RM)">
                        <input name="salary_monthly" type="number" class="form-control" placeholder="RM" value="{{ $employer->salary_monthly or old('salary_monthly') }}" :readonly="!edit">
                    </b-form-group>

                    <b-form-group horizontal :label-cols="2" label="Daily (RM)">
                        <input name="salary_daily" type="number" class="form-control" placeholder="RM" value="{{ $employer->salary_daily or old('salary_daily') }}" :readonly="!edit">
                    </b-form-group>

                    <b-form-group horizontal :label-cols="2" label="Hourly (RM)">
                        <input name="salary_hourly" type="number" class="form-control" placeholder="RM" value="{{ $employer->salary_hourly or old('salary_hourly') }}" :readonly="!edit">
                    </b-form-group>


                    <br>

                    <b-form-group horizontal :label-cols="2" label="">
                        <button type="button" class="btn btn-sm btn-blue-grey mt-0 float-right" v-on:click="viewMode" v-if="edit">Cancel</button>
                        <button class="btn btn-sm btn-primary m-0 float-right" v-if="edit">Save</button>
                    </b-form-group>


                </form>

            </div>

        </div>

    </div>
</div>


@endsection

@section('vue')
<script defer>
    const app = new Vue({
        el: '#app',
        data: {
            edit: false,
            households: {!! json_encode($employer->households) !!}
        },
        mounted: {

        },
        methods: {
            editMode: function () {
                this.edit = true;
                $('.mdb-select').removeClass('d-none');
            },
            viewMode: function () {

                var retVal = confirm("Do you want to quit editing? All your change with loss.");
                $('.mdb-select').addClass('d-none');

                if( retVal == true ){
                        this.edit = false;
                }
            },
            addHousehold: function(){
                this.households.push('');
            },
            removeHousehold: function(key){
                this.households.splice(key, 1);
            }
        }
    });

</script>
@endsection

@push('scripts')
{!! JsValidator::formRequest('App\Http\Requests\JobRelatedDetailsRequest', '#form-job-related-details') !!}
<script>
$('.datepicker').pickadate({
    format: 'dd/mm/yyyy',
    formatSubmit: 'yyyy/mm/dd',
});

$('[name="location_type"]').val('{{ $employer->location_type }}');
$('[name="employee_types[]"]').val({!! json_encode($employer->employee_types) !!});
$('.mdb-select').material_select();
</script>
@endpush