routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Route::get('/logout', 'Auth\LoginController@logout')->name('logout');

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/', 'HomeController@index')->name('home');
Route::get('/premium/employer', 'HomeController@employerPremium')->name('premium.employer');

Route::group(['middleware' => ['guest.redirect']], function () {

    // registration
    Route::get('/register/maid', 'RegisterEmployeeController@create')->name('register.employee.create');
    Route::post('/register/maid', 'RegisterEmployeeController@store')->name('register.employee.store');

    Route::get('/register/employer', 'RegisterEmployerController@create')->name('register.employer.create');
    Route::post('/register/employer', 'RegisterEmployerController@store')->name('register.employer.store');

    Route::group(['prefix' => 'employee'], function () {

        Route::resource('search', 'Employee\SearchController', ['as' => 'employee']);

    });

});

// please add route that need to login below
// please use resourcefull route for standard
Route::group(['middleware' => ['auth']], function () {

    Route::group(['prefix' => 'user'], function () {

        Route::resource('profile_picture', 'ProfilePictureController');
        Route::resource('account', 'AccountController', ['as' => 'profile']);

    });

    Route::group(['prefix' => 'employee'], function () {

        Route::resource('personal', 'Employee\PersonalInformationController', ['as' => 'employee']);
        Route::resource('job_details', 'Employee\JobDetailsController', ['as' => 'employee']);
    });

    Route::group(['prefix' => 'employer'], function () {

        Route::resource('personal', 'Employer\PersonalInformationController', ['as' => 'employer']);
        Route::resource('job_details', 'Employer\JobDetailsController', ['as' => 'employer']);
    });

    Route::resource('user', 'UserController');

    Route::group(['middleware' => ['admin'], 'prefix' => 'admin'], function () {

        Route::resource('dashboard', 'Admin\DashboardController', ['as' => 'admin']);

        Route::put('employee/{id}/verify', 'Admin\EmployeeController@verify')->name('admin.employee.verify');
        Route::put('employee/{id}/unverify', 'Admin\EmployeeController@unverify')->name('admin.employee.unverify');
        Route::resource('employee', 'Admin\EmployeeController', ['as' => 'admin']);

        Route::put('employer/{id}/verify', 'Admin\EmployerController@verify')->name('admin.employer.verify');
        Route::put('employer/{id}/unverify', 'Admin\EmployerController@unverify')->name('admin.employer.unverify');
        Route::resource('employer', 'Admin\EmployerController', ['as' => 'admin']);

    });

});

//test

Route::get('/print', 'PrintController@print');

app/Models/User.php
<?php

namespace App\Models;

use App\Traits\Uuids;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Facades\Storage;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use Notifiable;
    use HasRoles;
    use Uuids;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'type',
    ];

    /**
     * Indicates if the IDs are auto-incrementing.
     *
     * @var bool
     */
    public $incrementing = false;

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function userable()
    {
        return $this->morphTo();
    }

    public function profilePictures()
    {
        return $this->hasMany(ProfilePicture::class);
    }

    public function avatar()
    {
        return $this->profilePictures()->where('is_primary', 1)->first();
    }

    public function getAvatarPathAttribute()
    {
        if (empty($this->avatar())) {
            return asset('img/profile/original.png');
        }

        $updated_at       = $this->avatar()->updated_at->timestamp;
        return $base_path = Storage::disk('local')->url($this->profilePictures()->where('is_primary', 1)->first()->path . '.png?' . $updated_at);
    }

    public function getAvatarPathMediumAttribute()
    {
        if (empty($this->avatar())) {
            return asset('img/profile/200.png');
        }

        $updated_at       = $this->avatar()->updated_at->timestamp;
        return $base_path = Storage::disk('local')->url($this->profilePictures()->where('is_primary', 1)->first()->path . '_200.png?' . $updated_at);
    }

    public function getAvatarPathThumbAttribute()
    {
        if (empty($this->avatar())) {
            return asset('img/profile/88.png');
        }

        $updated_at       = $this->avatar()->updated_at->timestamp;
        return $base_path = Storage::disk('local')->url($this->profilePictures()->where('is_primary', 1)->first()->path . '_88.png?' . $updated_at);
    }

    public function getIsVerifiedAttribute()
    {
        if (!empty($this->attributes['verified'])) {
            return true;
        } else {
            return false;
        }
    }

}

app/Http/Controllers/Admin/EmployerController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Country;
use App\Models\Employer;
use App\Models\Nationality;
use App\Models\Race;
use App\Models\State;
use Carbon\Carbon;
use Illuminate\Http\Request;

class EmployerController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $employees = Employer::all();

        $data = [
            // 'breadcrumb' => [
            //     ['Admin', '#'],
            //     ['Employer', '#'],
            // ],
            'employers' => $employees,
        ];

        return view('admin.employer.index')->with($data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $employer = Employer::find($id);

        $detail = [
            'name'         => $employer->user->name,
            'display name' => $employer->display_name,
            'height'       => $employer->height . 'cm',
            'weight'       => $employer->weight . 'kg',
            'nationality'  => $employer->nationality_name,
            'race'         => $employer->race_name,
        ];

        $data = [
            'employer' => $employer,
            'details'  => $detail,
        ];

        return view('admin.employer.show')->with($data);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $employer      = Employer::find($id);
        $countries     = Country::toJsonOption();
        $nationalities = Nationality::toJsonOption();
        $races         = Race::toJsonOption();
        $states        = State::toJsonOption('name', 'name');
        $address       = $employee->getPrimaryAddress();

        $data = [
            'breadcrumb'    => [
                ['Admin', route('admin.employer.index')],
                ['Employer', route('admin.employer.index')],
                ['Update', '#'],
            ],
            'action'        => route('admin.employer.update', $id),
            'method'        => 'PUT',
            'employer'      => $employer,
            'address'       => $address,
            'countries'     => $countries,
            'nationalities' => $nationalities,
            'races'         => $races,
            'states'        => $states,
        ];

        return view('admin.employer.form')->with($data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function verify($id)
    {
        $employer = Employer::find($id);
        $user     = $employer->user;

        $user->verified = Carbon::now();
        $user->save();

        return response()->json([
            'success' => 'Employer verified',
        ]);
    }

    public function unverify($id)
    {
        $employer = Employer::find($id);
        $user     = $employer->user;

        $user->verified = null;
        $user->save();

        return response()->json([
            'success' => 'Employer unverified',
        ]);
    }
}

app/Http/Controllers/Employer/JobDetailsController.php
<?php

namespace App\Http\Controllers\Employer;

use App\Http\Controllers\Controller;
use App\Models\WorkSkill;
use Illuminate\Http\Request;

class JobDetailsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $user                 = auth()->user();
        $employee             = $user->userable;
        $employee_work_skills = $employee->workSkills->map(function ($item, $key) {
            return $item->id;
        })->toArray();
        $work_skills = WorkSkill::all();

        // dd($user->userable->workSkills->map(function ($item, $key) {
        //     return $item->id;
        // }));

        $data = [
            'user'                 => $user,
            'employer'             => $employee,
            'employee_work_skills' => $employee_work_skills,
            'work_skills'          => $work_skills,
        ];

        return view('employer.job_details')->with($data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $user     = auth()->user();
        $employer = $user->userable;

        if (!empty($request['skills'])) {
            $request['skills'] = array_keys($request['skills']);
        } else {
            $request['skills'] = [];
        }

        // dd($request->all());

        $employer->update(
            [
                'about'          => $request['about'],
                'location_type'  => $request['location_type'],
                'households'     => $request['households'],
                'employee_types' => $request['employee_types'],

                'salary_monthly' => $request['salary_monthly'],
                'salary_daily'   => $request['salary_daily'],
                'salary_hourly'  => $request['salary_hourly'],
            ]
        );

        $employer->workSkills()->detach();
        $employer->workSkills()->attach($request['skills']);

        \Session::flash('alert-success', 'Employer Related Information Updated');
        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Employer/PersonalInformationController.php
<?php

namespace App\Http\Controllers\Employer;

use App\Http\Controllers\Controller;
use App\Http\Requests\EmployerPersonalRequest;
use App\Models\Country;
use App\Models\Employer;
use App\Models\Nationality;
use App\Models\Race;
use App\Models\State;
use Illuminate\Http\Request;

class PersonalInformationController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $user     = auth()->user();
        $employer = $user->userable;

        if (empty($employer)) {
            $employer                       = new Employer();
            $employer->is_profile_completed = false;
            $employer->save();

            $user->userable_id   = $employer->id;
            $user->userable_type = Employer::class;
            $user->save();
        }

        $address = $employer->getPrimaryAddress();

        $countries      = Country::toJsonOption();
        $nationalities  = Nationality::toJsonOption();
        $races          = Race::toJsonOption();
        $states         = State::toJsonOption('name', 'name');
        $marital_status = json_encode([
            ['text' => 'Never married', 'value' => 1],
            ['text' => 'Married', 'value' => 2],
            ['text' => 'Divorced', 'value' => 3],
            ['text' => 'Separated', 'value' => 4],
            ['text' => 'Widowed', 'value' => 5],
        ]);

        $data = [
            'user'           => $user,
            'employer'       => $employer,
            'address'        => $address,
            'countries'      => $countries,
            'nationalities'  => $nationalities,
            'races'          => $races,
            'states'         => $states,
            'marital_status' => $marital_status,
        ];

        return view('profile.employer_details')->with($data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     *
     * @return \Illuminate\Http\Response
     */
    public function store(EmployerPersonalRequest $request)
    {
        // dd($request->all());

        $user     = auth()->user();
        $employer = $user->userable;

        $user->update(
            [
                'name' => $request['name'],
            ]
        );

        $employer->update(
            [
                'display_name'   => $request['display_name'],
                'nationality_id' => $request['nationality_id'],
                'race_id'        => $request['race_id'],

                'facebook'       => $request['facebook'],
                'linkedin'       => $request['linkedin'],
                'google_plus'    => $request['google_plus'],
            ]
        );

        $address = [
            'street'       => $request['street'],
            'street_extra' => $request['street_extra'],
            'state'        => $request['state'],
            'city'         => $request['city'],
            'post_code'    => $request['post_code'],
            'country_id'   => $request['country_id'],
            'is_primary'   => true,
        ];

        if ($employer->hasAddress()) {
            $current_address = $employer->addresses()->first();
            $employer->updateAddress($current_address, $address);
        } else {
            $employer->addAddress($address);
        }

        $employer->is_profile_completed = 1;
        $employer->save();

        \Session::flash('alert-success', 'Personal Information Updated');

        return redirect()->back();
    }
}

resources/views/admin/employer/form.blade.php
@extends('layouts.app')

@section('content')

<section>

<div class="row">
    <div class="col-md-8">
        <panel>
            <template slot="title">New Bus</template>
            <template slot="action">

            </template>
            <template slot="content">

                <!--begin::Form-->
                <form id="form-employee" action="{{ route('admin.employee.update', $employee->id) }}" method="post" >

                    <h4 class="card-title"><a>Personal Information</a></h4>
                    <hr>

                    @if(isset($method))
                    {{ method_field($method) }}
                    @endif
                    {{ csrf_field() }}

                    <b-form-group horizontal :label-cols="2" label="name">
                        <input name="name" type="text" class="form-control " placeholder="Name" value="{{ $employee->user->name or old('name') }}" >
                    </b-form-group>

                    <b-form-group horizontal :label-cols="2" label="Display Name">
                        <input name="display_name" type="text" class="form-control " placeholder="Display Name" value="{{ $employee->display_name or old('display_name') }}" >
                    </b-form-group>

                    <b-form-group horizontal :label-cols="2" label="Nationality">
                        <b-form-select name="nationality_id" v-bind:value="{{ $employee->nationality_id or old('nationality_id') }}" :options="{{ $nationalities }}" class="w-50"  >
                        </b-form-select>
                    </b-form-group>

                    <b-form-group horizontal :label-cols="2" label="Race">
                        <b-form-select name="race_id" v-bind:value="{{ $employee->race_id or old('race_id') }}" :options="{{ $races }}" placeholder="hello" class="w-50"  >
                        </b-form-select>
                    </b-form-group>

                    <br>
                    <h4 class="card-title"><a>Address</a></h4>
                    <hr>

                    <b-form-group horizontal :label-cols="2" label="Line 1">
                        <input name="street" type="text" class="form-control " placeholder="Line 1" value="{{ $address->street or old('street') }}" >
                    </b-form-group>

                    <b-form-group horizontal :label-cols="2" label="Line 2">
                        <input name="street_extra" type="text" class="form-control " placeholder="Line 2" value="{{ $address->street_extra or old('street_extra') }}" >
                    </b-form-group>

                    <b-form-group horizontal :label-cols="2" label="Postcode">
                        <input name="post_code" type="text" class="form-control w-50" placeholder="Postcode" value="{{ $address->post_code or old('post_code') }}" >
                    </b-form-group>

                    <b-form-group horizontal :label-cols="2" label="City">
                        <input name="city" type="text" class="form-control " placeholder="City" value="{{ $address->city or old('city') }}" >
                    </b-form-group>

                    <b-form-group horizontal :label-cols="2" label="State">
                        <input type="text" class="form-control " placeholder="State" value="{{ $address->state or old('state') }}">
                    </b-form-group>

                    <b-form-group horizontal :label-cols="2" label="Country">
                        <b-form-select name="country_id" v-bind:value="{{ $address->country_id or old('country_id') }}" :options="{{ $countries }}" class="w-50"  >
                        </b-form-select>
                    </b-form-group>

                    <br>
                    <h4 class="card-title"><a>Social App</a></h4>
                    <hr>

                    <div class="md-form input-group">
                        <div class="input-group-prepend">
                            <button class="btn btn-sm btn-fb m-0" type="button"><i class="fa fa-facebook pr-1"></i></button>
                        </div>
                        <input name="facebook" type="text" class="form-control" placeholder="Facebook" value="{{ $employee->facebook or old('facebook') }}" >
                    </div>

                    <div class="md-form input-group">
                        <div class="input-group-prepend">
                            <button class="btn btn-sm btn-li m-0" type="button"><i class="fa fa-linkedin"></i></button>
                        </div>
                        <input name="linkedin" type="text" class="form-control" placeholder="Linkedin" value="{{ $employee->linkedin or old('linkedin') }}" >
                    </div>

                    <div class="md-form input-group">
                        <div class="input-group-prepend">
                            <button class="btn btn-sm btn-gplus m-0" type="button"><i class="fa fa-google-plus"></i></button>
                        </div>
                        <input name="google_plus" type="text" class="form-control" placeholder="Google Plus" value="{{ $employee->google_plus or old('google_plus') }}" >
                    </div>

                    <br>

                </form>

            </template>
            <template slot="footer">
                <a href="{{ route('admin.employee.index') }}" class="btn btn-flat">Cancel</a>
                <a onclick="$('#form-employee').submit();" class="btn btn-success">Submit</a>
            </template>

        </panel>
    </div>
</div>

</section>

@endsection

@section('vue')
<script defer>
$( document ).ready(function() {
    const app = new Vue({
        el: '#app',
    });
});

</script>
@endsection

resources/views/admin/employer/index.blade.php
@extends('layouts.app')

@section('content')

<div class="row">
    <div class="col-md-3">

        @include('admin.navigation')

    </div>
    <div class="col-md-9">

    <panel>
        <template slot="title">Employer List</template>
        <template slot="action">

        </template>
        <template slot="table">
            <div class="table-responsive">

                <datatable>
                    <template slot="header">
                        <tr>
                            <th>Name</th>
                            <th>Display Name</th>
                            <th>Email</th>
                            <th>Register At</th>
                            <th>Verification</th>
                        </tr>
                    </template>
                    <template slot="body">
                        @foreach($employers as $employee)
                        <tr>
                            <td>
                                <a href="{{ route('admin.employer.show', $employee->id) }}">{{ $employee->user->name }}</a>
                            </td>
                            <td>{{ $employee->display_name }}</td>
                            <td>{{ $employee->user->email }}</td>
                            <td>{{ $employee->created_at->toFormattedDateString() }}</td>
                            @if( !empty($employee->user) )
                                @if( !empty($employee->user->verified) )
                                <td>Verified</td>
                                @else
                                <td>
                                    <a href="{{ route('admin.employer.show', $employee->id) }}" class="btn btn-rounded btn-sm btn-outline-success">
                                        Verify
                                    </a>
                                </td>
                                @endif
                            @else
                            <td></td>
                            @endif
                        </tr>
                        @endforeach
                    </template>
                </datatable>

            </div>
        </template>
        {{-- <template slot="footer">
            <h4>Footer here</h4>
        </template> --}}

    </panel>

    </div>
</div>

@endsection

@section('vue')
<script defer>
$( document ).ready(function() {
    const app = new Vue({
        el: '#app',
    });
});

</script>
@endsection

@push('css')
<link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap4.min.css">
@endpush

@push('scripts')
<script type="text/javascript" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js"></script>

<script>

</script>

@endpush

resources/views/admin/employer/show.blade.php
@extends('layouts.app')

@section('content')

<div class="row">
    <div class="col-md-3">

        @include('admin.navigation')

    </div>
    <div class="col-md-6">

        <div class="card testimonial-card">

            <!-- Bacground color -->
            <div class="card-up green lighten-1">
            </div>

            <!-- Avatar -->
            <div class="avatar mx-auto white">
                <img src="{{ $employer->user->avatarPathThumb }}" class="rounded-circle" style="min-height:110px;">
            </div>

            <div class="card-body">
                <!-- Name -->
                <h5 class="card-title">{{ $employer->user->name }}</h5>
                <h6 class="card-subtitle text-muted">{{ $employer->user->email }}</h6>
                <h6 class="card-subtitle mb-2 mt-2">
                    Facebook: <a href="{{ $employer->facebook or '#' }}" target="_blank" >{{ $employer->facebook or 'not available' }}</a>
                </h6>
            </div>

            <div class="row">
                <div class="col-md-12">

                    <table class="table table-sm table-borderless">
                        <tbody>
                            @foreach( $details as $key => $data )
                            <tr>
                                <td class="text-right text-capitalize" width="30%">{{ $key }} :</td>
                                <td class="text-left">{{ $data }}</td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>

                </div>
            </div>

            <div class="p-2">
            @if( !$employer->user->is_verified )
                <btn-icon class="btn-lg btn-block" btn-size="lg" btn-type="warning" href="{{ route('admin.employer.verify', $employer->id) }}"
                ajax="PUT" confirm="Verify" reload="true">Verify</btn-icon>
            @else
                <btn-icon class="btn-lg btn-block" btn-size="lg" btn-type="danger" href="{{ route('admin.employer.unverify', $employer->id) }}"
                ajax="PUT" confirm="Unverify" reload="true">Unverify</btn-icon>
            @endif
            </div>

        </div>


    </div>
</div>

@endsection

@section('vue')
<script defer>
$( document ).ready(function() {
    const app = new Vue({
        el: '#app',
    });
});

</script>
@endsection

@push('scripts')
<script>

</script>

@endpush