routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Route::get('/logout', 'Auth\LoginController@logout')->name('logout');

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/', 'HomeController@index')->name('home');
Route::get('/premium/employer', 'HomeController@employerPremium')->name('premium.employer');

Route::group(['middleware' => ['guest.redirect']], function () {

    // registration
    Route::get('/register/maid', 'RegisterEmployeeController@create')->name('register.employee.create');
    Route::post('/register/maid', 'RegisterEmployeeController@store')->name('register.employee.store');

    Route::get('/register/employer', 'RegisterEmployerController@create')->name('register.employer.create');
    Route::post('/register/employer', 'RegisterEmployerController@store')->name('register.employer.store');

    Route::group(['prefix' => 'employee'], function () {

        Route::resource('search', 'Employee\SearchController', ['as' => 'employee']);

    });

});

// please add route that need to login below
// please use resourcefull route for standard
Route::group(['middleware' => ['auth']], function () {

    Route::group(['prefix' => 'user'], function () {

        Route::resource('profile_picture', 'ProfilePictureController');
        Route::resource('account', 'AccountController', ['as' => 'profile']);

    });

    Route::group(['prefix' => 'employee'], function () {

        Route::resource('personal', 'Employee\PersonalInformationController', ['as' => 'employee']);
        Route::resource('job_details', 'Employee\JobDetailsController', ['as' => 'employee']);
    });

    Route::group(['prefix' => 'employer'], function () {

        Route::resource('personal', 'Employer\PersonalInformationController', ['as' => 'employer']);
        Route::resource('job_details', 'Employer\JobDetailsController', ['as' => 'employer']);
    });

    Route::resource('user', 'UserController');

    Route::group(['middleware' => ['admin'], 'prefix' => 'admin'], function () {

        Route::resource('dashboard', 'Admin\DashboardController', ['as' => 'admin']);

        Route::put('employee/{id}/verify', 'Admin\EmployeeController@verify')->name('admin.employee.verify');
        Route::put('employee/{id}/unverify', 'Admin\EmployeeController@unverify')->name('admin.employee.unverify');
        Route::resource('employee', 'Admin\EmployeeController', ['as' => 'admin']);

        Route::put('employer/{id}/verify', 'Admin\EmployerController@verify')->name('admin.employer.verify');
        Route::put('employer/{id}/unverify', 'Admin\EmployerController@unverify')->name('admin.employer.unverify');
        Route::resource('employer', 'Admin\EmployerController', ['as' => 'admin']);

    });

});

//test

Route::get('/print', 'PrintController@print');

resources/views/templates/footer.blade.php
<footer class="page-footer text-center text-md-left pt-4 unique-color-dark">

    <!--Copyright-->
    <div class="footer-copyright py-3 text-center">
        <div class="container-fluid">
            © 2018 Copyright: <a href="http://www.mypembantu.com"> MyPembantu.com </a>

        </div>
    </div>
    <!--/.Copyright-->

</footer>

resources/views/templates/navbar.blade.php
<!-- SideNav slide-out button -->
<!-- <div class="float-left d-block d-xs-none">
    <a href="#" data-activates="slide-out" class="button-collapse black-text"><i class="fa fa-bars"></i></a>
</div> -->

@if(empty($sidebar))
<a class="ml-2 navbar-brand" href="{{ route('home') }}">
    <img src="{{ asset('img/logo.png') }}" height="30" alt="">
</a>
@else
<a class="ml-2 navbar-brand ml-5" href="{{ route('home') }}">
    <img src="{{ asset('img/logo.png') }}" height="30" alt="">
</a>
@endif

@if(!auth()->check())
<div class="form-inline my-2 my-lg-0 ml-auto">
    <a class="btn btn-outline-pink btn-md my-2 my-sm-0 ml-3" href="{{ route('login') }}">Sign in</a>
</div>
@endif
@if(auth()->check())
<ul class="nav navbar-nav nav-flex-icons ml-auto">
    <li class="nav-item">
        <a class="nav-link waves-effect waves-light">1
            <i class="fa fa-bell"></i>
        </a>
    </li>
    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fa fa-user"></i> <span class="clearfix d-none d-sm-inline-block">Account</span>
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">

            @if(auth()->user()->userable_type == 'App\Models\Employee')
            <a class="dropdown-item" href="{{ route('employee.personal.index') }}">Profile</a>
            @elseif(auth()->user()->userable_type == 'App\Models\Employer')
            <a class="dropdown-item" href="{{ route('employer.personal.index') }}">Profile</a>
            @endif

            <a class="dropdown-item" href="{{ url('logout') }}">Logout</a>
        </div>
    </li>
</ul>
@endif

resources/views/templates/sidebar-menu.blade.php
<li class="mt-5">
    <ul class="collapsible collapsible-accordion">
        <li class="menu-item">
            <a class="collapsible-header waves-effect" href="{{ route('admin.dashboard.index') }}">
                <i class="fa fa-dashboard"></i>Dashboard
            </a>
        </li>
        <li class="menu-item">
            <a class="collapsible-header waves-effect" href="{{ route('admin.employee.index') }}">
                <i class="fa fa-users"></i>Maid
            </a>
        </li>
        <li class="menu-item">
            <a class="collapsible-header waves-effect" href="{{ route('admin.employer.index') }}">
                <i class="fa fa-user-circle"></i>Employer
            </a>
        </li>
    </ul>
</li>

resources/views/templates/sidebar.blade.php
<div id="slide-out" class="side-nav sn-bg-4 fixed">
    <ul class="custom-scrollbar">
        <!-- Logo -->
        <li>
            <div class="logo-wrapper waves-light">
                <a class="navbar-brand" href="{{ route('home') }}">
                    <img src="{{ asset('img/logo.png') }}" alt="" style="height:80px; padding:20px;">
                </a>
            </div>
        </li>
        <!--/. Logo -->

        <!-- Side navigation links -->
        @include('templates.sidebar-menu')
        <!--/. Side navigation links -->
    </ul>
    <div class="sidenav-bg mask-strong"></div>
</div>